name: Deploy Github Pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deply:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Create Node Environment
        uses: actions/setup-node@v1
        with: 
          node-version: 10.x
      
      - name: Install and build project
        run: |
          cd homepage
          npm install
          npm run build

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
